services:
  postgres:
    image: postgres:latest
    container_name: postgres-golearn
    ports:
      - "5433:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=golearn