services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5445:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=car_zone